CREATE
SET
  TABLE SOC.O_TELP (
    PART_ID INTEGER NOT NULL PRIMARY KEY,
    CNTR_IND VARCHAR(5),
    TELP_NUM VARCHAR(20) NOT NULL,
    STRT_VALD_DTTM TIMESTAMP(0) NOT NULL,
    END_VALD_DTTM TIMESTAMP(0) NOT NULL,
    EXEC_ID INTEGER NOT NULL
  ) UNIQUE PRIMARY INDEX (PART_ID);


  TABLE SOC.O_ADDR(
    PART_ID INTEGER NOT NULL,
    STRT_NUM VARCHAR(10) NOT NULL,
    STRT_DSC VARCHAR(250) NOT NULL,
    COMP_STRT VARCHAR(250),
    POST_CD VARCHAR(10) NOT NULL,
    CITY_NAME VARCHAR(100),
    CNTR_NAME VARCHAR(100),
    STRT_VALD_DTTM TIMESTAMP(0) NOT NULL,
    END_VALD_DTTM TIMESTAMP(0) NOT NULL,
    EXEC_ID INTEGER,
    PRIMARY KEY(PART_ID, STRT_VALD_DTTM)

  ) UNIQUE PRIMARY INDEX (PART_ID);

  TABLE SOC.O_CONS(
    CONS_ID	INTEGER NOT NULL PRIMARY KEY,
    STFF_ID	INTEGER NOT NULL,
    PATN_ID	INTEGER NOT NULL,
    CONS_STRT_DTTM	TIMESTAMP(0) NOT NULL,
    CONS_END_DTTM	TIMESTAMP(0) NOT NULL,
    PATN_WEGH	INTEGER NOT NULL,
    PATN_TEMP	INTEGER,
    TEMP_UNIT	VARCHAR(15),
    BLD_PRSS	INTEGER,
    PATH_DSC	VARCHAR(250),
    DIBT_IND	BYTEINT,
    TRET_ID	TIMESTAMP(0),
    HOSP_IND	BYTEINT,
    EXEC_ID	INTEGER NOT NULL

  )UNIQUE PRIMARY INDEX (PATN_ID);

  TABLE SOC.O_HOSP(
    HOSP_ID	INTEGER NOT NULL PRIMARY KEY,
    CONS_ID	INTEGER NOT NULL,
    ROOM_NUM	SMALLINT NOT NULL,
    HOSP_STRT_DTTM	TIMESTAMP(0) NOT NULL,
    HOSP_END_DTTM	TIMESTAMP(0) NOT NULL,
    HOSP_FINL_RATE	TIMESTAMP(0) NOT NULL,
    STFF_ID	INTEGER NOT NULL,
    EXEC_ID	INTEGER NOT NULL
  )UNIQUE PRIMARY INDEX (CONS_ID);

  TABLE SOC.R_MEDC(
    MEDC_ID	INTEGER NOT NULL PRIMARY KEY,
    MEDC_CD	VARCHAR(10) NOT NULL,
    MEDC_NAME	VARCHAR(250),
    MEDC_COND	VARCHAR(100),
    MEDC_CATG	VARCHAR(100) NOT NULL,
    MANF_BRND	VARCHAR(100) NOT NULL,
    EXEC_ID	INTEGER NOT NULL

  )UNIQUE PRIMARY INDEX (MEDC_ID);