.LOGON localhost/dbc,dbc;

UPDATE WRK.WRK_CONSULTATION
SET INDIC_DIABETE = CASE WHEN INDIC_DIABETE = 'True' THEN 1 ELSE 0 END,
    INDIC_HOSPI = CASE WHEN INDIC_HOSPI = 'True' THEN 1 ELSE 0 END;

.LOGOFF;
.EXIT;
