.LOGON localhost/dbc,dbc;

-- Create a volatile table to store the unique combinations and the new MEDC_ID
CREATE VOLATILE TABLE VT_UNIQUE_COMB AS (
    SELECT
        CD_MEDICAMENT,
        CATG_MEDICAMENT,
        MARQUE_FABRI,
        ROW_NUMBER() OVER (PARTITION BY CD_MEDICAMENT, CATG_MEDICAMENT, MARQUE_FABRI ORDER BY TS_CREATION_TRAITEMENT) AS ROW_NUM
    FROM WRK.WRK_TRAITEMENT
) WITH DATA PRIMARY INDEX (CD_MEDICAMENT, CATG_MEDICAMENT, MARQUE_FABRI)
ON COMMIT PRESERVE ROWS;

-- Update the WRK_TRAITEMENT table with the new MEDC_ID
UPDATE WRK.WRK_TRAITEMENT T1
FROM VT_UNIQUE_COMB T2
SET T1.MEDC_ID = (
    SELECT MAX(T3.MEDC_ID) + T2.ROW_NUM
    FROM WRK.WRK_TRAITEMENT T3
    WHERE T3.CD_MEDICAMENT = T2.CD_MEDICAMENT
    AND T3.CATG_MEDICAMENT = T2.CATG_MEDICAMENT
    AND T3.MARQUE_FABRI = T2.MARQUE_FABRI
)
WHERE T1.CD_MEDICAMENT = T2.CD_MEDICAMENT
AND T1.CATG_MEDICAMENT = T2.CATG_MEDICAMENT
AND T1.MARQUE_FABRI = T2.MARQUE_FABRI;

.IF ERRORCODE <> 0 THEN .QUIT 100;

-- Drop the volatile table as it is no longer needed
DROP TABLE VT_UNIQUE_COMB;

.LOGOFF;
.EXIT;
