LOGON localhost/dbc,dbc;

MERGE INTO SOC.R_ROOM AS R_ROOM
USING WRK.WRK_CHAMBRE AS WRK_CHAMBRE
ON R_ROOM.ROOM_NUM = WRK_CHAMBRE.NO_CHAMBRE
WHEN MATCHED THEN
    UPDATE SET
        R_ROOM.ROOM_NAME = WRK_CHAMBRE.NOM_CHAMBRE,
        R_ROOM.FLOOR_NUM = WRK_CHAMBRE.NO_ETAGE,
        R_ROOM.BUILD_NAME = WRK_CHAMBRE.NOM_BATIMENT,
        R_ROOM.ROOM_TYP = WRK_CHAMBRE.TYPE_CHAMBRE,
        R_ROOM.ROOM_DAY_RATE = WRK_CHAMBRE.PRIX_JOUR, 
        R_ROOM.CRTN_DT = WRK_CHAMBRE.DT_CREATION, 
        R_ROOM.EXEC_ID = 1
WHEN NOT MATCHED THEN
    INSERT (R_ROOM.ROOM_NUM, R_ROOM.ROOM_NAME, R_ROOM.FLOOR_NUM, R_ROOM.BUILD_NAME, R_ROOM.ROOM_TYP, R_ROOM.ROOM_DAY_RATE, R_ROOM.CRTN_DT, R_ROOM.EXEC_ID)
    VALUES (WRK_CHAMBRE.NOM_CHAMBRE, WRK_CHAMBRE.NO_ETAGE, WRK_CHAMBRE.NOM_BATIMENT, WRK_CHAMBRE.TYPE_CHAMBRE, WRK_CHAMBRE.PRIX_JOUR, WRK_CHAMBRE.DT_CREATION, 1);

.IF ERRORCODE <> 0 THEN .QUIT 100;

.LOGOFF;
.EXIT;


