LOGON localhost/dbc,dbc;

INSERT INTO SOC.O_CONS (
    CONS_ID,
    STFF_ID,
    PATN_ID,
    CONS_STRT_DTTM,
    CONS_END_DTTM,
    PATN_WEGH,
    PATN_TEMP,
    TEMP_UNIT,
    BLD_PRSS,
    PATH_DSC,
    DIBT_IND,
    TRET_ID,
    HOSP_IND,
    EXEC_ID
)
SELECT
    ID_CONSULT,
    ID_PERSONNEL,
    ID_PATIENT,
    TS_DEBUT_CONSULT,
    TS_FIN_CONSULT,
    POIDS_PATIENT,
    TEMP_PATIENT,
    UNIT_TEMP,
    TENSION_PATIENT,
    DSC_PATHO,
    INDIC_DIABETE,
    ID_TRAITEMENT,
    INDIC_HOSPI,
    1
FROM WRK.WRK_CONSULTATION;

.IF ERRORCODE <> 0 THEN .QUIT 100;

.LOGOFF;
.EXIT;
