LOGON localhost/dbc,dbc;

MERGE INTO SOC.O_HOSP AS O_HOSP
USING WRK.WRK_HOSPITALISATION  AS WRK_HOSPITALISATION 
ON O_HOSP.HOSP_ID = WRK_HOSPITALISATION.ID_HOSPI
WHEN MATCHED THEN   
    UPDATE SET
        O_HOSP.CONS_ID = WRK_HOSPITALISATION.ID_CONSULT,
        O_HOSP.ROOM_NUM = WRK_HOSPITALISATION.NO_CHAMBRE,
        O_HOSP.HOSP_STRT_DTTM = WRK_HOSPITALISATION.TS_DEBUT_HOSPI,
        O_HOSP.HOSP_END_DTTM = WRK_HOSPITALISATION.TS_FIN_HOSPI,
        O_HOSP.HOSP_FINL_RATE = WRK_HOSPITALISATION.COUT_HOSPI,
        O_HOSP.STFF_ID = WRK_HOSPITALISATION.ID_PERSONNEL_RESP,
        O_HOSP.EXEC_ID = 1
WHEN NOT MATCHED THEN 
    INSERT (
        O_HOSP.CONS_ID, 
        O_HOSP.ROOM_NUM, 
        O_HOSP.HOSP_STRT_DTTM, 
        O_HOSP.HOSP_END_DTTM,
         O_HOSP.HOSP_FINL_RATE, 
         O_HOSP.STFF_ID, 
         O_HOSP.EXEC_ID
    )
    VALUES (
        WRK_HOSPITALISATION.ID_CONSULT,
        WRK_HOSPITALISATION.NO_CHAMBRE, 
        WRK_HOSPITALISATION.TS_DEBUT_HOSPI, 
        WRK_HOSPITALISATION.TS_FIN_HOSPI, 
        WRK_HOSPITALISATION.COUT_HOSPI,
        WRK_HOSPITALISATION.ID_PERSONNEL_RESP,
        1
    )

.IF ERRORCODE <> 0 THEN .QUIT 100;

.LOGOFF;
.EXIT;


