LOGON localhost/dbc,dbc;

INSERT INTO SOC.O_HOSP (
    HOSP_ID,
    CONS_ID, 
    ROOM_NUM, 
    HOSP_STRT_DTTM, 
    HOSP_END_DTTM, 
    HOSP_FINL_RATE, 
    STFF_ID, 
    EXEC_ID
)
SELECT
    WRK_HOSPITALISATION.ID_HOSPI,
    WRK_HOSPITALISATION.ID_CONSULT,
    WRK_HOSPITALISATION.NO_CHAMBRE, 
    WRK_HOSPITALISATION.TS_DEBUT_HOSPI, 
    WRK_HOSPITALISATION.TS_FIN_HOSPI, 
    WRK_HOSPITALISATION.COUT_HOSPI,
    WRK_HOSPITALISATION.ID_PERSONNEL_RESP,
    1
FROM WRK.WRK_HOSPITALISATION;

.IF ERRORCODE <> 0 THEN .QUIT 100;

.LOGOFF;
.EXIT;