LOGON localhost/dbc,dbc;

MERGE INTO SOC.O_IND AS O_IND
USING WRK.WRK_INDIVIDU AS WRK_INDIVIDU
ON O_IND.PART_ID = WRK_INDIVIDU.PART_ID
WHEN MATCHED THEN
    UPDATE SET
        O_IND.INDV_NAME = WRK_INDIVIDU.NOM_INDIVIDU,
        O_IND.INDV_NAME = WRK_INDIVIDU.INDV_NAME,
        O_IND.INDV_FIRS_NAME = WRK_INDIVIDU.INDV_FIRS_NAME,
        O_IND.INDV_STTS_CD = WRK_INDIVIDU.INDV_STTS_CD,
        O_IND.CRTN_DTTM = WRK_INDIVIDU.TS_CREATION,
        O_IND.UPDT_DTTM = WRK_INDIVIDU.TS_MAJ,
        O_IND.BIRT_DT = WRK_INDIVIDU.DT_NAISS,
        O_IND.BIRT_CITY = WRK_INDIVIDU.VILLE_NAISS,
        O_IND.BIRT_CNTR = WRK_INDIVIDU.PAYS_NAISS,
        O_IND.SOCL_NUM = WRK_INDIVIDU.NUM_SECU,
        O_IND.EXEC_ID = 1


WHEN NOT MATCHED THEN
    INSERT (O_IND.INDV_NAME, O_IND.INDV_FIRS_NAME, O_IND.INDV_STTS_CD, O_IND.CRTN_DTTM, O_IND.UPDT_DTTM, O_IND.BIRT_DT, O_IND.BIRT_CITY, O_IND.BIRT_CNTR, O_IND.SOCL_NUM, O_IND.EXEC_ID)
    VALUES (WRK_INDIVIDU.NOM_INDIVIDU, WRK_INDIVIDU.INDV_NAME, WRK_INDIVIDU.INDV_FIRS_NAME, WRK_INDIVIDU.INDV_STTS_CD, WRK_INDIVIDU.TS_CREATION, WRK_INDIVIDU.TS_MAJ, WRK_INDIVIDU.DT_NAISS, WRK_INDIVIDU.VILLE_NAISS, WRK_INDIVIDU.PAYS_NAISS, WRK_INDIVIDU.NUM_SECU, 1);

.IF ERRORCODE <> 0 THEN .QUIT 100;

.LOGOFF;
.EXIT;


