LOGON localhost/dbc,dbc;

UPDATE SOC.O_IND
FROM WRK.WRK_INDIVIDU
SET

    O_IND.INDV_NAME = WRK_INDIVIDU.INDV_NAME,
    O_IND.INDV_FIRS_NAME = WRK_INDIVIDU.INDV_FIRS_NAME,
    O_IND.INDV_STTS_CD = WRK_INDIVIDU.INDV_STTS_CD,
    O_IND.CRTN_DTTM = WRK_INDIVIDU.TS_CREATION,
    O_IND.UPDT_DTTM = WRK_INDIVIDU.TS_MAJ,
    O_IND.BIRT_DT = WRK_INDIVIDU.DT_NAISS,
    O_IND.BIRT_CITY = WRK_INDIVIDU.VILLE_NAISS,
    O_IND.BIRT_CNTR = WRK_INDIVIDU.PAYS_NAISS,
    O_IND.SOCL_NUM = WRK_INDIVIDU.NUM_SECU,
    O_IND.EXEC_ID = 1
WHERE O_IND.PART_ID = WRK_INDIVIDU.PART_ID ;

INSERT INTO SOC.O_IND (
    PART_ID,
    INDV_NAME,
    INDV_FIRS_NAME,
    INDV_STTS_CD,
    CRTN_DTTM,
    UPDT_DTTM,
    BIRT_DT,
    BIRT_CITY,
    BIRT_CNTR,
    SOCL_NUM,
    EXEC_ID
) 
SELECT 
    PART_ID,
    INDV_NAME,
    INDV_FIRS_NAME,
    INDV_STTS_CD,
    TS_CREATION,
    TS_MAJ,
    DT_NAISS,
    VILLE_NAISS,
    PAYS_NAISS,
    NUM_SECU,
    1
) FROM WRK.WRK_INDIVIDU
WHERE NOT EXISTS (
    SELECT 1 FROM SOC.O_IND
    WHERE SOC.O_IND.PART_ID = WRK_INDIVIDU.PART_ID
);

.IF ERRORCODE <> 0 THEN .QUIT 100;

.LOGOFF;
.EXIT;


