LOGON localhost/dbc,dbc;

UPDATE SOC.O_STFF
FROM WRK.WRK_STAFF
SET
    WORK_STRT_DTTM = WRK.WRK_STAFF.,
    WORK_END_DTTM = WRK.WRK_STAFF.,
    WORK_END_RESN = WRK.WRK_STAFF.,
    EXEC_ID = 1
WHERE O_STFF.PART_ID = WRK.WRK_CHAMBRE.NO_CHAMBRE;


INSERT INTO SOC.O_STFF (
    PART_ID,
    WORK_STRT_DTTM, 
    WORK_END_DTTM, 
    WORK_END_RESN, 
    EXEC_ID
)
SELECT
    
FROM WRK.WRK_STAFF
WHERE NOT EXISTS (
    SELECT 1 FROM SOC.O_STFF
    WHERE SOC.O_STFF.PART_ID = WRK.WRK_STAFF.PART_ID
);

.IF ERRORCODE <> 0 THEN .QUIT 100;

.LOGOFF;
.EXIT;
