.LOGON localhost/dbc,dbc;

-- Step 1: Update existing records' end date with the new start date from the source
UPDATE SOC.O_STFF
SET
    WORK_END_DTTM = (SELECT WRK.WRK_STAFF.WORK_STRT_DTTM 
                     FROM WRK.WRK_STAFF 
                     WHERE WRK.WRK_STAFF.PART_ID = SOC.O_STFF.PART_ID)
WHERE EXISTS (
    SELECT 1 
    FROM WRK.WRK_STAFF
    WHERE WRK.WRK_STAFF.PART_ID = SOC.O_STFF.PART_ID
);

.IF ERRORCODE <> 0 THEN .QUIT 100;

-- Step 2: Insert new records from the source table
INSERT INTO SOC.O_STFF (
    PART_ID,
    WORK_STRT_DTTM, 
    WORK_END_DTTM, 
    WORK_END_RESN, 
    EXEC_ID
)
SELECT
    WRK.WRK_STAFF.PART_ID,
    WRK.WRK_STAFF.WORK_STRT_DTTM,
    WRK.WRK_STAFF.WORK_END_DTTM,
    WRK.WRK_STAFF.WORK_END_RESN,
    1
FROM WRK.WRK_STAFF
WHERE NOT EXISTS (
    SELECT 1 
    FROM SOC.O_STFF
    WHERE SOC.O_STFF.PART_ID = WRK.WRK_STAFF.PART_ID
);

.IF ERRORCODE <> 0 THEN .QUIT 100;

.LOGOFF;
.EXIT;
