.LOGON localhost/dbc,dbc;

UPDATE SOC.O_TRET
FROM WRK.WRK_TRAITEMENT
SET
    MEDC_ID = WRK.WRK_TRAITEMENT.MEDC_ID,
    MEDC_QTY = WRK.WRK_TRAITEMENT.QTE_MEDICAMENT,
    DOSG_DSC = WRK.WRK_TRAITEMENT.DSC_POSOLOGIE,
    CONS_ID = WRK.WRK_TRAITEMENT.ID_CONSULT,
    TRET_CRTN_DTTM = WRK.WRK_TRAITEMENT.TS_CREATION_TRAITEMENT, 
    EXEC_ID = 1
WHERE O_TRET.TRET_ID = WRK.WRK_TRAITEMENT.ID_TRAITEMENT;

INSERT INTO SOC.O_TRET (
    TRET_ID,
    MEDC_ID,
    MEDC_QTY,
    DOSG_DSC,
    CONS_ID,
    TRET_CRTN_DTTM,
    EXEC_ID
)

SELECT
    ID_TRAITEMENT,
    MEDC_ID,
    QTE_MEDICAMENT,
    DSC_POSOLOGIE,
    ID_CONSULT,
    TS_CREATION_TRAITEMENT, 
    1
FROM WRK.WRK_TRAITEMENT
WHERE NOT EXISTS (
    SELECT 1 FROM SOC.O_TRET
    WHERE SOC.O_TRET.TRET_ID = WRK.WRK_TRAITEMENT.ID_TRAITEMENT
);


.IF ERRORCODE <> 0 THEN .QUIT 100;

.LOGOFF;
.EXIT;

