.LOGON localhost/dbc,dbc;

INSERT INTO SOC.O_TRET (TRET_ID, MEDC_ID, MEDC_QTY, DOSG_DSC, CONS_ID, TRET_CRTN_DTTM, EXEC_ID)
SELECT ID_TRAITEMENT,
       CD_MEDICAMENT || CATG_MEDICAMENT AS MEDC_ID,
       QTE_MEDICAMENT,
       DSC_POSOLOGIE,
       ID_CONSULT,
       TS_CREATION_TRAITEMENT,
       EXEC_ID
FROM WRK.WRK_TRAITEMENT;

.IF ERRORCODE <> 0 THEN .QUIT 100;

.LOGOFF;
.EXIT;

