LOGON localhost/dbc,dbc;

-- Initialisation suivi TCH
INSERT INTO TCH.T_SUIVI_TRMT(RUN_ID, SCRPT_NAME, EXEC_STRT_DTTM, EXEC_STTS_CD)
VALUES((SELECT MAX(RUN_ID) FROM TCH.T_SUIVI_RUN), 'work_to_soc_chambre.sql', NOW(), 'ENC');

CREATE VOLATILE TABLE CURRENT_EXEC_ID
(
current_exec_id int
) PRIMARY INDEX (current_exec_id)
ON COMMIT PRESERVE ROWS;

INSERT INTO CURRENT_EXEC_ID(current_exec_id) SELECT MAX(EXEC_ID) FROM TCH.T_SUIVI_TRMT;

-- Step 1: Update existing records with new information
UPDATE SOC.R_ROOM
FROM WRK.WRK_CHAMBRE
SET
    ROOM_NAME = WRK.WRK_CHAMBRE.NOM_CHAMBRE,
    FLOR_NUM = WRK.WRK_CHAMBRE.NO_ETAGE,
    BULD_NAME = WRK.WRK_CHAMBRE.NOM_BATIMENT,
    ROOM_TYP = WRK.WRK_CHAMBRE.TYPE_CHAMBRE,
    ROOM_DAY_RATE = WRK.WRK_CHAMBRE.PRIX_JOUR,
    CRTN_DT = WRK.WRK_CHAMBRE.DT_CREATION,
    EXEC_ID = (SELECT current_exec_id FROM CURRENT_EXEC_ID)
WHERE R_ROOM.ROOM_NUM = WRK.WRK_CHAMBRE.NO_CHAMBRE;

.IF ERRORCODE <> 0 THEN .GOTO LABEL_UPDATE_WITH_ERROR;

-- Step 2: Insert new records
INSERT INTO SOC.R_ROOM (
    ROOM_NUM,
    ROOM_NAME, 
    FLOR_NUM, 
    BULD_NAME, 
    ROOM_TYP, 
    ROOM_DAY_RATE, 
    CRTN_DT, 
    EXEC_ID
)
SELECT
    NO_CHAMBRE,
    NOM_CHAMBRE, 
    NO_ETAGE, 
    NOM_BATIMENT,
    TYPE_CHAMBRE, 
    PRIX_JOUR, 
    DT_CREATION,
    (SELECT current_exec_id FROM CURRENT_EXEC_ID)
FROM WRK.WRK_CHAMBRE
WHERE NOT EXISTS (
    SELECT 1 FROM SOC.R_ROOM
    WHERE SOC.R_ROOM.ROOM_NUM = WRK.WRK_CHAMBRE.NO_CHAMBRE
);

-- MAJ etat et date de fin du script dans suivi TCH
.IF ERRORCODE <> 0 THEN .GOTO LABEL_UPDATE_WITH_ERROR;
UPDATE TCH.T_SUIVI_TRMT
SET EXEC_END_DTTM=NOW(), EXEC_STTS_CD='OK'
WHERE EXEC_ID = (SELECT current_exec_id FROM CURRENT_EXEC_ID);
.GOTO LABEL_UPDATE_SUCCESS

.LABEL LABEL_UPDATE_WITH_ERROR
UPDATE TCH.T_SUIVI_TRMT
SET EXEC_END_DTTM=NOW(), EXEC_STTS_CD='KO'
WHERE EXEC_ID = (SELECT current_exec_id FROM CURRENT_EXEC_ID);
.QUIT 100;

.LABEL LABEL_UPDATE_SUCCESS

.LOGOFF;
.EXIT;
