.LOGON localhost/dbc,dbc;

-- Initialisation suivi TCH
INSERT INTO TCH.T_SUIVI_TRMT(RUN_ID, SCRPT_NAME, EXEC_STRT_DTTM, EXEC_STTS_CD)
VALUES((SELECT MAX(RUN_ID) FROM TCH.T_SUIVI_RUN), 'work_to_soc_medicament.sql', NOW(), 'Running');

CREATE VOLATILE TABLE CURRENT_EXEC_ID
(
current_exec_id int
) PRIMARY INDEX (current_exec_id)
ON COMMIT PRESERVE ROWS;

INSERT INTO CURRENT_EXEC_ID(current_exec_id) SELECT MAX(EXEC_ID) FROM TCH.T_SUIVI_TRMT;

-- Step 1: Update existing records with new information
UPDATE SOC.R_MEDC tgt
SET
    tgt.MEDC_CD = src.CD_MEDICAMENT,
    tgt.MEDC_NAME = src.NOM_MEDICAMENT,
    tgt.MEDC_COND = src.CONDIT_MEDICAMENT,
    tgt.MEDC_CATG = src.CATG_MEDICAMENT,
    tgt.MANF_BRND = src.MARQUE_FABRI,
    tgt.EXEC_ID = (SELECT current_exec_id FROM CURRENT_EXEC_ID)
FROM WRK.WRK_MEDICAMENT src
WHERE tgt.MEDC_ID = src.MEDC_ID
  AND (
       src.CD_MEDICAMENT <> tgt.MEDC_CD
    OR src.NOM_MEDICAMENT <> tgt.MEDC_NAME
    OR src.CONDIT_MEDICAMENT <> tgt.MEDC_COND
    OR src.CATG_MEDICAMENT <> tgt.MEDC_CATG
    OR src.MARQUE_FABRI <> tgt.MANF_BRND
  );

.IF ERRORCODE <> 0 THEN .QUIT 100;

-- Step 2: Insert new records
INSERT INTO SOC.R_MEDC (
    MEDC_ID, 
    MEDC_CD, 
    MEDC_NAME, 
    MEDC_COND, 
    MEDC_CATG, 
    MANF_BRND, 
    EXEC_ID
)
SELECT
    src.MEDC_ID,
    src.CD_MEDICAMENT,
    src.NOM_MEDICAMENT,
    src.CONDIT_MEDICAMENT,
    src.CATG_MEDICAMENT,
    src.MARQUE_FABRI,
    (SELECT current_exec_id FROM CURRENT_EXEC_ID)
FROM WRK.WRK_MEDICAMENT src
WHERE NOT EXISTS (
    SELECT 1 
    FROM SOC.R_MEDC tgt
    WHERE tgt.MEDC_ID = src.MEDC_ID
);

-- MAJ etat et date de fin du script dans suivi TCH
.IF ERRORCODE <> 0 THEN .GOTO LABEL_UPDATE_WITH_ERROR;
UPDATE TCH.T_SUIVI_TRMT
SET EXEC_END_DTTM=NOW(), EXEC_STTS_CD='Success'
WHERE EXEC_ID = (SELECT current_exec_id FROM CURRENT_EXEC_ID);
.GOTO LABEL_UPDATE_SUCCESS

.LABEL LABEL_UPDATE_WITH_ERROR
UPDATE TCH.T_SUIVI_TRMT
SET EXEC_END_DTTM=NOW(), EXEC_STTS_CD='Error'
WHERE EXEC_ID = (SELECT current_exec_id FROM CURRENT_EXEC_ID);
.QUIT 100;

.LABEL LABEL_UPDATE_SUCCESS

.LOGOFF;
.EXIT;
