.LOGON localhost/dbc,dbc;

-- Initialisation suivi TCH
INSERT INTO TCH.T_SUIVI_TRMT(RUN_ID, SCRPT_NAME, EXEC_STRT_DTTM, EXEC_STTS_CD)
VALUES((SELECT MAX(RUN_ID) FROM TCH.T_SUIVI_RUN), 'work_to_soc_traitement.sql', NOW(), 'Running');

CREATE VOLATILE TABLE CURRENT_EXEC_ID
(
current_exec_id int
) PRIMARY INDEX (current_exec_id)
ON COMMIT PRESERVE ROWS;

INSERT INTO CURRENT_EXEC_ID(current_exec_id) SELECT MAX(EXEC_ID) FROM TCH.T_SUIVI_TRMT;

UPDATE SOC.O_TRET
FROM WRK.WRK_TRAITEMENT
SET
    MEDC_ID = WRK.WRK_TRAITEMENT.MEDC_ID,
    MEDC_QTY = WRK.WRK_TRAITEMENT.QTE_MEDICAMENT,
    DOSG_DSC = WRK.WRK_TRAITEMENT.DSC_POSOLOGIE,
    CONS_ID = WRK.WRK_TRAITEMENT.ID_CONSULT,
    TRET_CRTN_DTTM = WRK.WRK_TRAITEMENT.TS_CREATION_TRAITEMENT, 
    EXEC_ID =  (SELECT current_exec_id FROM CURRENT_EXEC_ID)
WHERE O_TRET.TRET_ID = WRK.WRK_TRAITEMENT.ID_TRAITEMENT;

INSERT INTO SOC.O_TRET (
    TRET_ID,
    MEDC_ID,
    MEDC_QTY,
    DOSG_DSC,
    CONS_ID,
    TRET_CRTN_DTTM,
    EXEC_ID
)

SELECT
    ID_TRAITEMENT,
    MEDC_ID,
    QTE_MEDICAMENT,
    DSC_POSOLOGIE,
    ID_CONSULT,
    TS_CREATION_TRAITEMENT, 
    (SELECT current_exec_id FROM CURRENT_EXEC_ID)
FROM WRK.WRK_TRAITEMENT
WHERE NOT EXISTS (
    SELECT 1 FROM SOC.O_TRET
    WHERE SOC.O_TRET.TRET_ID = WRK.WRK_TRAITEMENT.ID_TRAITEMENT
);

-- MAJ etat et date de fin du script dans suivi TCH
.IF ERRORCODE <> 0 THEN .GOTO LABEL_UPDATE_WITH_ERROR;
UPDATE TCH.T_SUIVI_TRMT
SET EXEC_END_DTTM=NOW(), EXEC_STTS_CD='Success'
WHERE EXEC_ID = (SELECT current_exec_id FROM CURRENT_EXEC_ID);
.GOTO LABEL_UPDATE_SUCCESS

.LABEL LABEL_UPDATE_WITH_ERROR
UPDATE TCH.T_SUIVI_TRMT
SET EXEC_END_DTTM=NOW(), EXEC_STTS_CD='Error'
WHERE EXEC_ID = (SELECT current_exec_id FROM CURRENT_EXEC_ID);
.QUIT 100;

.LABEL LABEL_UPDATE_SUCCESS

.LOGOFF;
.EXIT;

