LOGON localhost/dbc,dbc;

-- Initialisation suivi TCH
INSERT INTO TCH.T_SUIVI_TRMT(RUN_ID, SCRPT_NAME, EXEC_STRT_DTTM, EXEC_STTS_CD)
VALUES((SELECT MAX(RUN_ID) FROM TCH.T_SUIVI_RUN), 'work_to_soc_rpart.sql', NOW(), 'ENC');

CREATE VOLATILE TABLE CURRENT_EXEC_ID
(
current_exec_id int
) PRIMARY INDEX (current_exec_id)
ON COMMIT PRESERVE ROWS;

INSERT INTO CURRENT_EXEC_ID(current_exec_id) SELECT MAX(EXEC_ID) FROM TCH.T_SUIVI_TRMT;

-- Step 1: Update existing records with new information
UPDATE SOC.R_PART
FROM WRK.WRK_RPART
SET
    PART_ID = WRK.WRK_RPART.PART_ID,
    SRC_ID = WRK.WRK_RPART.INDIVIDU_ID,
    SRC_TYP = WRK.WRK_RPART.FONCTION_INDIVIDU
WHERE (
    WRK.WRK_RPART.PART_ID = SOC.R_PART.PART_ID
);

.IF ERRORCODE <> 0 THEN .QUIT 100;

-- Step 2: Insert new records from the source table
INSERT INTO SOC.R_PART (
    PART_ID, 
    SRC_ID, 
    SRC_TYP
)
SELECT
    PART_ID,
    INDIVIDU_ID,
    FONCTION_INDIVIDU
FROM WRK.WRK_RPART
WHERE NOT EXISTS (
    SELECT 1
    FROM SOC.R_PART
    WHERE SOC.R_PART.PART_ID = WRK.WRK_RPART.PART_ID
);

-- MAJ etat et date de fin du script dans suivi TCH
.IF ERRORCODE <> 0 THEN .GOTO LABEL_UPDATE_WITH_ERROR;
UPDATE TCH.T_SUIVI_TRMT
SET EXEC_END_DTTM=NOW(), EXEC_STTS_CD='OK'
WHERE EXEC_ID = (SELECT current_exec_id FROM CURRENT_EXEC_ID);
.GOTO LABEL_UPDATE_SUCCESS

.LABEL LABEL_UPDATE_WITH_ERROR
UPDATE TCH.T_SUIVI_TRMT
SET EXEC_END_DTTM=NOW(), EXEC_STTS_CD='KO'
WHERE EXEC_ID = (SELECT current_exec_id FROM CURRENT_EXEC_ID);
.QUIT 100;

.LABEL LABEL_UPDATE_SUCCESS

.LOGOFF;
.EXIT;
