LOGON localhost/dbc,dbc;

-- Initialisation suivi TCH
INSERT INTO TCH.T_SUIVI_TRMT(RUN_ID, SCRPT_NAME, EXEC_STRT_DTTM, EXEC_STTS_CD)
VALUES((SELECT MAX(RUN_ID) FROM TCH.T_SUIVI_RUN), 'work_to_soc_individu.sql', NOW(), 'ENC');

CREATE VOLATILE TABLE CURRENT_EXEC_ID
(
current_exec_id int
) PRIMARY INDEX (current_exec_id)
ON COMMIT PRESERVE ROWS;

INSERT INTO CURRENT_EXEC_ID(current_exec_id) SELECT MAX(EXEC_ID) FROM TCH.T_SUIVI_TRMT;

-- Step 1: Update existing records with new information
UPDATE SOC.O_INDV
FROM WRK.WRK_INDIVIDU
SET
    INDV_NAME = WRK_INDIVIDU.INDV_NAME,
    INDV_FIRS_NAME = WRK_INDIVIDU.INDV_FIRS_NAME,
    INDV_STTS_CD = WRK_INDIVIDU.INDV_STTS_CD,
    CRTN_DTTM = WRK_INDIVIDU.TS_CREATION,
    UPDT_DTTM = WRK_INDIVIDU.TS_MAJ,
    BIRT_DT = WRK_INDIVIDU.DT_NAISS,
    BIRT_CITY = WRK_INDIVIDU.VILLE_NAISS,
    BIRT_CNTR = WRK_INDIVIDU.PAYS_NAISS,
    SOCL_NUM = WRK_INDIVIDU.NUM_SECU,
    EXEC_ID = (SELECT current_exec_id FROM CURRENT_EXEC_ID)
WHERE O_INDV.PART_ID = WRK_INDIVIDU.PART_ID;

-- Step 2: Insert new records from the source table
INSERT INTO SOC.O_INDV (
    PART_ID,
    INDV_NAME,
    INDV_FIRS_NAME,
    INDV_STTS_CD,
    CRTN_DTTM,
    UPDT_DTTM,
    BIRT_DT,
    BIRT_CITY,
    BIRT_CNTR,
    SOCL_NUM,
    EXEC_ID
) 
SELECT 
    PART_ID,
    INDV_NAME,
    INDV_FIRS_NAME,
    INDV_STTS_CD,
    TS_CREATION,
    TS_MAJ,
    DT_NAISS,
    VILLE_NAISS,
    PAYS_NAISS,
    NUM_SECU,
    (SELECT current_exec_id FROM CURRENT_EXEC_ID)
    FROM WRK.WRK_INDIVIDU
WHERE NOT EXISTS (
    SELECT 1 
    FROM SOC.O_INDV
    WHERE SOC.O_INDV.PART_ID = WRK_INDIVIDU.PART_ID
);

-- MAJ etat et date de fin du script dans suivi TCH
.IF ERRORCODE <> 0 THEN .GOTO LABEL_UPDATE_WITH_ERROR;
UPDATE TCH.T_SUIVI_TRMT
SET EXEC_END_DTTM=NOW(), EXEC_STTS_CD='Success'
WHERE EXEC_ID = (SELECT current_exec_id FROM CURRENT_EXEC_ID);
.GOTO LABEL_UPDATE_SUCCESS

.LABEL LABEL_UPDATE_WITH_ERROR
UPDATE TCH.T_SUIVI_TRMT
SET EXEC_END_DTTM=NOW(), EXEC_STTS_CD='KO'
WHERE EXEC_ID = (SELECT current_exec_id FROM CURRENT_EXEC_ID);
.QUIT 100;

.LABEL LABEL_UPDATE_SUCCESS

.LOGOFF;
.EXIT;


