.LOGON localhost/dbc,dbc;

-- Initialisation suivi TCH
INSERT INTO TCH.T_SUIVI_TRMT(RUN_ID, SCRPT_NAME, EXEC_STRT_DTTM, EXEC_STTS_CD)
VALUES((SELECT MAX(RUN_ID) FROM TCH.T_SUIVI_RUN), 'work_to_soc_medicament.sql', NOW(), 'ENC');

CREATE VOLATILE TABLE CURRENT_EXEC_ID
(
current_exec_id int
) PRIMARY INDEX (current_exec_id)
ON COMMIT PRESERVE ROWS;

INSERT INTO CURRENT_EXEC_ID(current_exec_id) SELECT MAX(EXEC_ID) FROM TCH.T_SUIVI_TRMT;

-- Step 1: Update existing records with new information
UPDATE SOC.R_MEDC
FROM WRK.WRK_MEDICAMENT
SET
    MEDC_CD = WRK.WRK_MEDICAMENT.CD_MEDICAMENT,
    MEDC_NAME = WRK.WRK_MEDICAMENT.NOM_MEDICAMENT,
    MEDC_COND = WRK.WRK_MEDICAMENT.CONDIT_MEDICAMENT,
    MEDC_CATG = WRK.WRK_MEDICAMENT.CATG_MEDICAMENT,
    MANF_BRND = WRK.WRK_MEDICAMENT.MARQUE_FABRI,
    EXEC_ID = (SELECT current_exec_id FROM CURRENT_EXEC_ID)
WHERE (
    SOC.R_MEDC.MEDC_ID = WRK.WRK_MEDICAMENT.MEDC_ID
  );

.IF ERRORCODE <> 0 THEN .QUIT 100;

-- Step 2: Insert new records
INSERT INTO SOC.R_MEDC (
    MEDC_ID, 
    MEDC_CD, 
    MEDC_NAME, 
    MEDC_COND, 
    MEDC_CATG, 
    MANF_BRND, 
    EXEC_ID
)
SELECT
    MEDC_ID,
    CD_MEDICAMENT,
    NOM_MEDICAMENT,
    CONDIT_MEDICAMENT,
    CATG_MEDICAMENT,
    MARQUE_FABRI,
    (SELECT current_exec_id FROM CURRENT_EXEC_ID)
FROM WRK.WRK_MEDICAMENT
WHERE NOT EXISTS (
    SELECT 1 
    FROM SOC.R_MEDC 
    WHERE SOC.R_MEDC.MEDC_ID = WRK.WRK_MEDICAMENT.MEDC_ID
);

-- MAJ etat et date de fin du script dans suivi TCH
.IF ERRORCODE <> 0 THEN .GOTO LABEL_UPDATE_WITH_ERROR;
UPDATE TCH.T_SUIVI_TRMT
SET EXEC_END_DTTM=NOW(), EXEC_STTS_CD='Success'
WHERE EXEC_ID = (SELECT current_exec_id FROM CURRENT_EXEC_ID);
.GOTO LABEL_UPDATE_SUCCESS

.LABEL LABEL_UPDATE_WITH_ERROR
UPDATE TCH.T_SUIVI_TRMT
SET EXEC_END_DTTM=NOW(), EXEC_STTS_CD='KO'
WHERE EXEC_ID = (SELECT current_exec_id FROM CURRENT_EXEC_ID);
.QUIT 100;

.LABEL LABEL_UPDATE_SUCCESS

.LOGOFF;
.EXIT;
