.LOGON localhost/dbc,dbc;

SELECT *
FROM TCH.T_SUIVI_TRMT
WHERE RUN_ID = (SELECT MAX(RUN_ID) FROM TCH.T_SUIVI_RUN)
AND EXEC_STTS_CD = 'Error';

.IF ACTIVITYCOUNT > 0 THEN .GOTO LABEL_UPDATE_WITH_ERROR;

UPDATE TCH.T_SUIVI_RUN
SET RUN_END_DTTM = NOW(),
    RUN_STTS_CD = 'Success'
WHERE RUN_ID = (SELECT MAX(RUN_ID) FROM TCH.T_SUIVI_RUN);

.GOTO LABEL_UPDATE_SUCCESS;

.LABEL LABEL_UPDATE_WITH_ERROR
UPDATE TCH.T_SUIVI_RUN
SET RUN_END_DTTM = NOW(),
    RUN_STTS_CD = 'Error'
WHERE RUN_ID = (SELECT MAX(RUN_ID) FROM TCH.T_SUIVI_RUN);

.LABEL LABEL_UPDATE_SUCCESS

.IF ERRORCODE <> 0 THEN .QUIT 100;

.LOGOFF;
.EXIT;
