CREATE DATABASE STG AS PERMANENT = 60e6, -- 60MB
SPOOL = 120e6;

-- 120MB

DROP TABLE IF EXISTS CHAMBRE;
DROP TABLE IF EXISTS TRAINTEMENT;
DROP TABLE IF EXISTS PERSONNEL;
DROP TABLE IF EXISTS MEDICAMENT;

CREATE 
SET
    TABLE IF NOT EXISTS CHAMBRE (
        NO_CHAMBRE INTEGER NOT NULL,
        NOM_CHAMBRE VARCHAR(20) NOT NULL,
        NO_ETAGE BYTEINT,
        NOM_BATIMENT VARCHAR(20),
        TYPE_CHAMBRE VARCHAR(20),
        PRIX_JOUR SMALLINT NOT NULL,
        DT_CREATION DATE NOT NULL,
    );

CREATE
SET
    TABLE IF NOT EXISTS TRAITEMENT (
        ID_TRAINTEMENT INTEGER NOT NULL,
        CD_MEDICAMENT INTEGER NOT NULL,
        CATG_MEDICAMENT VARCHAR(100) NOT NULL,
        MARQUE_FABRI VARCHAR(100) NOT NULL,
        QTE_MEDICAMENT SMALLINT,
        DSC_POSOLOGIE VARCHAR(100) NOT NULL,
        ID_CONSULT INTEGER NOT NULL,
        TS_CREATION_TRAITEMENT TIMESTAMP(0) NOT NULL,
    );

CREATE 
SET
    TABLE IF NOT EXISTS PERSONNEL (
        ID_PERSONNEL INTEGER NOT NULL,
        NOM_PERSONNEL VARCHAR(100) NOT NULL,
        PRENOM_PERSONNEL VARCHAR(100) NOT NULL,
        FONCTION_PERSONNEL VARCHAR(50) NOT NULL,
        TS_DEBUT_ACTIVITE TIMESTAMP(0) NOT NULL,
        TS_FIN_ACTIVITE TIMESTAMP(0),
        RAISON_FIN_ACTIVITE  VARCHAR(100),
        TS_CREATION_PERSONNEL TIMESTAMP(0) NOT NULL,
        TS_MAJ_PERSONNEL TIMESTAMP(0) NOT NULL,
        CD_STATUT_PERSONNEL  VARCHAR(10) NOT NULL,
    );

CREATE
SET
    TABLE STG.PATIENT (
        ID_PERSONNEL INTEGER NOT NULL,
        NOM_PERSONNEL VARCHAR(100) NOT NULL,
        PRENOM_PERSONNEL VARCHAR(100) NOT NULL,
        FONCTION_PERSONNEL VARCHAR(50) NOT NULL,
        TS_DEBUT_ACTIVITE TIMESTAMP(0) NOT NULL,
        TS_FIN_ACTIVITE TIMESTAMP(0),
        RAISON_FIN_ACTIVITE VARCHAR(100),
        TS_CREATION_PERSONNEL TIMESTAMP(0) NOT NULL,
        TS_MAJ_PERSONNEL TIMESTAMP(0) NOT NULL,
        CD_STATUT_PERSONNEL VARCHAR(10) NOT NULL
    )

CREATE
SET
    TABLE STG.CONSULTATION (
        ID_CONSULT INTEGER NOT NULL,
        ID_PERSONNEL INTEGER NOT NULL,
        ID_PATIENT INTEGER NOT NULL,
        TS_DEBUT_CONSULT TIMESTAMP(0) NOT NULL,
        TS_FIN_CONSULT TIMESTAMP(0) NOT NULL,
        POIDS_PATIENT INTEGER NOT NULL,
        TEMP_PATIENT INTEGER,
        UNIT_TEMP VARCHAR(15),
        TENSION_PATIENT INTEGER, 
        DSC_PATHO VARCHAR(250),
        INDIC_DIABETE VARCHAR(10),
        ID_TRAITEMENT INTEGER,
        INDIC_HOSPI VARCHAR(10)
    )
        

CREATE 
SET
    TABLE STG.HOSPITALISATION (
        ID_HOSPI INTEGER NOT NULL,
        ID_CONSULT INTEGER NOT NULL,
        NO_CHAMBRE SMALLINT NOT NULL,
        TS_DEBUT_HOSPI TIMESTAMP(0) NOT NULL,
        TS_FIN_HOSPI TIMESTAMP(0),
        COUT_HOSPI INTEGER,
        ID_PERSONNEL_RESP INTEGER NOT NULL
    )


CREATE 
SET
    TABLE IF NOT EXISTS MEDICAMENT (
        CD_MEDICAMENT VARCHAR(10) NOT NULL,
        NOM_MEDICAMENT VARCHAR(250),
        CONDIT_MEDICAMENT VARCHAR(100),
        CATG_MEDICAMENT VARCHAR(100) NOT NULL,
        MARQUE_FABRI VARCHAR(100) NOT NULL,
    );


