DROP TABLE IF EXISTS TCH.T_SUIVI_RUN
DROP TABLE IF EXISTS TCH.T_SUIVI_TRMT


CREATE
SET
  TABLE TCH.T_SUIVI_RUN (
    RUN_ID INTEGER NOT NULL,
    RUN_STRT_DTTM TIMESTAMP(0) NOT NULL,
    RUN_ED_DTTM TIMESTAMP(0),
    RUN_STTS_CD VARCHAR(10) NOT NULL
  ) UNIQUE PRIMARY INDEX (RUN_ID);
  
  CREATE 
  SET 
  	TABLE TCH.T_SUIVI_TRMT (
  	RUN_ID INTEGER NOT NULL,
    SCRPT_NAME VARCHAR(250) NOT NULL,
    EXEC_STRT_DTTM TIMESTAMP(0) NOT NULL,
    EXEC_END_DTTM TIMESTAMP(0), 
    EXEC_STTS_CD VARCHAR(10) NOT NULL, 
    EXEC_ID INTEGER NOT NULL 
  ) UNIQUE PRIMARY INDEX (EXEC_ID);
  
  
  