LOGON localhost/dbc,dbc;

INSERT INTO WRK.WRK_CHAMBRE (NO_CHAMBRE, NOM_CHAMBRE, NO_ETAGE, NOM_BATIMENT, TYPE_CHAMBRE, PRIX_JOUR, DT_CREATION) 
SELECT * FROM STG.CHAMBRE;

INSERT INTO WRK.WRK_TRAITEMENT (ID_TRAITEMENT, CD_MEDICAMENT, CATG_MEDICAMENT, MARQUE_FABRI, QTE_MEDICAMENT,
    DSC_POSOLOGIE, ID_CONSULT, TS_CREATION_TRAITEMENT) 
SELECT * FROM STG.TRAITEMENT;

INSERT INTO WRK.WRK_PERSONNEL (ID_PERSONNEL, NOM_PERSONNEL, PRENOM_PERSONNEL, FONCTION_PERSONNEL, TS_DEBUT_ACTIVITE,
    TS_FIN_ACTIVITE, RAISON_FIN_ACTIVITE, TS_CREATION_PERSONNEL, TS_MAJ_PERSONNEL, CD_STATUT_PERSONNEL) 
SELECT * FROM STG.PERSONNEL;

INSERT INTO WRK.WRK_PATIENT (ID_PATIENT, NOM_PATIENT, PRENOM_PATIENT, DT_NAISS, VILLE_NAISS, PAYS_NAISS, NUM_SECU, IND_PAYS_NUM_TELP, 
    NUM_TELEPHONE, NUM_VOIE, DSC_VOIE,CMPL_VOIE, CD_POSTAL, VILLE, PAYS, TS_CREATION_PATIENT, TS_MAJ_PERSONNEL) 
SELECT * FROM STG.PATIENT;

INSERT INTO WRK.WRK_CONSULTATION (ID_CONSULT, ID_PERSONNEL, ID_PATIENT, TS_DEBUT_CONSULT, TS_FIN_CONSULT,
    POIDS_PATIENT, TEMP_PATIENT, UNIT_TEMP, TENSION_PATIENT, DSC_PATHO, INDIC_DIABETE, ID_TRAITEMENT , INDIC_HOSPI) 
SELECT * FROM STG.CONSULTATION;

INSERT INTO WRK.WRK_HOSPITALISATION (ID_HOSPI, ID_CONSULT, NO_CHAMBRE, TS_DEBUT_HOSPI, TS_FIN_HOSPI, COUT_HOSPI, ID_PERSONNEL_RESP) 
SELECT * FROM STG.HOSPITALISATION;

INSERT INTO WRK.WRK_MEDICAMENT (ID_HOSPI, ID_CONSULT, NO_CHAMBRE, TS_DEBUT_HOSPI, TS_FIN_HOSPI, COUT_HOSPI, ID_PERSONNEL_RESP) 
SELECT * FROM STG.MEDICAMENT;

.IF ERRORCODE <> 0 THEN .QUIT 100;

.LOGOFF;
.EXIT;