LOGON localhost/dbc,dbc;

-- Initialisation suivi TCH
INSERT INTO TCH.T_SUIVI_TRMT(RUN_ID, SCRPT_NAME, EXEC_STRT_DTTM, EXEC_STTS_CD)
VALUES((SELECT MAX(RUN_ID) FROM TCH.T_SUIVI_RUN), 'stg_to_work_consultation.sql', NOW(), 'Running');

CREATE VOLATILE TABLE CURRENT_EXEC_ID
(
current_exec_id int
) PRIMARY INDEX (current_exec_id)
ON COMMIT PRESERVE ROWS;

INSERT INTO CURRENT_EXEC_ID(current_exec_id) SELECT MAX(EXEC_ID) FROM TCH.T_SUIVI_TRMT;

-- STG to work pour consultation
INSERT INTO WRK.WRK_CONSULTATION(
    ID_CONSULT,
    ID_PERSONNEL, 
    ID_PATIENT,
    TS_DEBUT_CONSULT,
    TS_FIN_CONSULT,
    POIDS_PATIENT,
    TEMP_PATIENT,
    UNIT_TEMP,
    TENSION_PATIENT, 
    DSC_PATHO,
    INDIC_DIABETE,
    ID_TRAITEMENT,
    INDIC_HOSPI,
    EXEC_ID
)
SELECT
    ID_CONSULT,
    ID_PERSONNEL, 
    ID_PATIENT,
    TS_DEBUT_CONSULT,
    TS_FIN_CONSULT,
    POIDS_PATIENT,
    TEMP_PATIENT,
    UNIT_TEMP,
    TENSION_PATIENT, 
    DSC_PATHO,
    INDIC_DIABETE,
    ID_TRAITEMENT,
    INDIC_HOSPI,
    (SELECT current_exec_id FROM CURRENT_EXEC_ID)
FROM STG.CONSULTATION;

-- MAJ etat et date de fin du script dans suivi TCH
.IF ERRORCODE <> 0 THEN .GOTO LABEL_UPDATE_WITH_ERROR;
UPDATE TCH.T_SUIVI_TRMT
SET EXEC_END_DTTM=NOW(), EXEC_STTS_CD='Success'
WHERE EXEC_ID = (SELECT current_exec_id FROM CURRENT_EXEC_ID);
.GOTO LABEL_UPDATE_SUCCESS

.LABEL LABEL_UPDATE_WITH_ERROR
UPDATE TCH.T_SUIVI_TRMT
SET EXEC_END_DTTM=NOW(), EXEC_STTS_CD='Error'
WHERE EXEC_ID = (SELECT current_exec_id FROM CURRENT_EXEC_ID);
.QUIT 100;

.LABEL LABEL_UPDATE_SUCCESS
.LOGOFF;
.EXIT;