LOGON localhost/dbc,dbc;

-- Initialisation suivi TCH
INSERT INTO TCH.T_SUIVI_TRMT(RUN_ID, SCRPT_NAME, EXEC_STRT_DTTM, EXEC_STTS_CD)
VALUES((SELECT MAX(RUN_ID) FROM TCH.T_SUIVI_RUN), 'stg_to_work_rpart.sql', NOW(), 'Running');

CREATE VOLATILE TABLE CURRENT_EXEC_ID
(
current_exec_id int
) PRIMARY INDEX (current_exec_id)
ON COMMIT PRESERVE ROWS;

INSERT INTO CURRENT_EXEC_ID(current_exec_id) SELECT MAX(EXEC_ID) FROM TCH.T_SUIVI_TRMT;

-- STG to work pour rpart
INSERT INTO WRK.WRK_RPART(
    PART_ID,
    INDIVIDU_ID,
    FONCTION_INDIVIDU,
    EXEC_ID
)
SELECT
    ROW_NUMBER() OVER (PARTITION BY 'Patient' ORDER BY ID_PATIENT) AS PART_ID, ID_PATIENT, 'Patient' AS FONCTION_INDIVIDU,
    (SELECT current_exec_id FROM CURRENT_EXEC_ID)
FROM STG.PATIENT;

.IF ERRORCODE <> 0 THEN .GOTO LABEL_UPDATE_WITH_ERROR;

INSERT INTO WRK.WRK_RPART(
    PART_ID,
    INDIVIDU_ID,
    FONCTION_INDIVIDU,
    EXEC_ID
)
SELECT
    ROW_NUMBER() OVER (PARTITION BY FONCTION_PERSONNEL ORDER BY ID_PERSONNEL) AS PART_ID,
    ID_PERSONNEL,
    FONCTION_PERSONNEL,
    (SELECT current_exec_id FROM CURRENT_EXEC_ID)
FROM STG.PERSONNEL;

-- MAJ etat et date de fin du script dans suivi TCH
.IF ERRORCODE <> 0 THEN .GOTO LABEL_UPDATE_WITH_ERROR;
UPDATE TCH.T_SUIVI_TRMT
SET EXEC_END_DTTM=NOW(), EXEC_STTS_CD='Success'
WHERE EXEC_ID = (SELECT current_exec_id FROM CURRENT_EXEC_ID);
.GOTO LABEL_UPDATE_SUCCESS

.LABEL LABEL_UPDATE_WITH_ERROR
UPDATE TCH.T_SUIVI_TRMT
SET EXEC_END_DTTM=NOW(), EXEC_STTS_CD='Error'
WHERE EXEC_ID = (SELECT current_exec_id FROM CURRENT_EXEC_ID);
.QUIT 100;

.LABEL LABEL_UPDATE_SUCCESS
.LOGOFF;
.EXIT;