LOGON localhost/dbc,dbc;

INSERT INTO WRK.WRK_CHAMBRE (NO_CHAMBRE, NOM_CHAMBRE, NO_ETAGE, NOM_BATIMENT, TYPE_CHAMBRE, PRIX_JOUR, DT_CREATION) 
SELECT * FROM STG.CHAMBRE;

.IF ERRORCODE <> 0 THEN .QUIT 100;

.LOGOFF;
.EXIT;