.LOGON localhost/dbc,dbc;

-- Initialize tracking for TCH
INSERT INTO TCH.T_SUIVI_TRMT (RUN_ID, SCRPT_NAME, EXEC_STRT_DTTM, EXEC_STTS_CD)
VALUES ((SELECT MAX(RUN_ID) FROM TCH.T_SUIVI_RUN), 'stg_to_work_consultation.sql', NOW(), 'ENC');

-- Create a volatile table to store current EXEC_ID
CREATE VOLATILE TABLE CURRENT_EXEC_ID (
    current_exec_id INT
) PRIMARY INDEX (current_exec_id)
ON COMMIT PRESERVE ROWS;

-- Insert the current EXEC_ID into the volatile table
INSERT INTO CURRENT_EXEC_ID (current_exec_id)
SELECT MAX(EXEC_ID) FROM TCH.T_SUIVI_TRMT;

-- Transfer data from STG.CONSULTATION to WRK.WRK_CONSULTATION
INSERT INTO WRK.WRK_CONSULTATION (
    ID_CONSULT,
    ID_PERSONNEL, 
    ID_PATIENT,
    TS_DEBUT_CONSULT,
    TS_FIN_CONSULT,
    POIDS_PATIENT,
    TEMP_PATIENT,
    UNIT_TEMP,
    TENSION_PATIENT, 
    DSC_PATHO,
    INDIC_DIABETE,
    ID_TRAITEMENT,
    INDIC_HOSPI,
    EXEC_ID
)
SELECT
    ID_CONSULT,
    ID_PERSONNEL, 
    ID_PATIENT,
    TS_DEBUT_CONSULT,
    TS_FIN_CONSULT,
    POIDS_PATIENT,
    TEMP_PATIENT,
    UNIT_TEMP,
    TENSION_PATIENT, 
    DSC_PATHO,
    INDIC_DIABETE,
    ID_TRAITEMENT,
    INDIC_HOSPI,
    (SELECT current_exec_id FROM CURRENT_EXEC_ID)
FROM STG.CONSULTATION;

IF ERRORCODE <> 0 THEN .GOTO LABEL_UPDATE_WITH_ERROR;

-- Transform INDIC_DIABETE/INDIC_HOSPI VALUES FROM True/False to 1/0
UPDATE WRK.WRK_CONSULTATION
SET INDIC_DIABETE = CASE WHEN INDIC_DIABETE = 'True' THEN 1 ELSE 0 END,
    INDIC_HOSPI = CASE WHEN INDIC_HOSPI = 'True' THEN 1 ELSE 0 END;

-- Update script status and end time in TCH tracking
.IF ERRORCODE <> 0 THEN .GOTO LABEL_UPDATE_WITH_ERROR;
UPDATE TCH.T_SUIVI_TRMT
SET EXEC_END_DTTM = NOW(),
    EXEC_STTS_CD = 'Success'
WHERE EXEC_ID = (SELECT current_exec_id FROM CURRENT_EXEC_ID);
.GOTO LABEL_UPDATE_SUCCESS;

.LABEL LABEL_UPDATE_WITH_ERROR
UPDATE TCH.T_SUIVI_TRMT
SET EXEC_END_DTTM = NOW(),
    EXEC_STTS_CD = 'KO'
WHERE EXEC_ID = (SELECT current_exec_id FROM CURRENT_EXEC_ID);
.QUIT 100;

.LABEL LABEL_UPDATE_SUCCESS
.LOGOFF;
.EXIT;
